[server]
headless = false

[runner]
fastReruns = true

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#1890FF"
backgroundColor = "#0d1117"
secondaryBackgroundColor = "#161b22"
textColor = "#e6edf3"
font = "sans serif"
